# -*- coding: utf-8 -*-
"""11

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TWXlpaZzdUS-H8JHFQydYmqeD3B5--Zm
"""

numero = int(input("Ingresa un número: "))

print(f"Tabla de multiplicar del {numero}:")

for i in range(1, 11):

    resultado = numero * i

    print(f"{numero} x {i} = {resultado}")



numero = int(input("Ingresa un número: "))
# Comprobar si el número es primo

es_primo = True

if numero <= 1:

    es_primo = False

else:

    for i in range(2, int(numero**0.5) + 1):

        if numero % i == 0:

            es_primo = False

            break



# Mostrar el resultado

if es_primo:

    print(f"{numero} es un número primo.")

else:

    print(f"{numero} no es un número primo.")





numero = int(input("Ingresa un número: "))



# Inicializar la variable para almacenar la suma

suma_total = 0



# Sumar desde 1 hasta el número ingresado

for i in range(1, numero + 1):

    suma_total += i



# Mostrar el resultado

print(f"La suma desde 1 hasta {numero} es: {suma_total}")